### ISSUE TITLE
Release notes in release tag message?

### ISSUE THREAD

**Issue by mxmilkiib** [ahlstromcj/seq66#24]
I'd like to add seq66 to https://libreav.org/updates

Could I request that the release change notes are used in the release message? Then they could be syndicated via the releases.atom.

**Comment by ahlstromcj** [comment]
Can you explain what that means, what I would have to do?

Thanks for your support!  Major fixes in the nsm branch now!  I am hoping to
finish off testing the NSM support in a few days, we shall see, the refactoring
job was a lot bigger than I ever anticipated!

-------- Milkii Brewster 08:34 Sat 07 Nov      --------

>I'd like to add seq66 to https://libreav.org/updates
>
>Could I request that the release change notes are used in the release message? Then they could be syndicated via the releases.atom.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/seq66/issues/24

-- 
An ounce of hypocrisy is worth a pound of ambition.
		-- Michael Korda

**Comment by mxmilkiib** [comment]
Either using the release description box in the Create Release feature on GitHub (which can accept markdown) or with something like `git tag -a v0.4 -m "$(cat RELNOTES.md)"` (which GH doesn't detect markdown from).

Awesome stuff, thank you, glad it has helped you iron things out, it will make things much easier for users :)

**Comment by mxmilkiib** [comment]
Could it be possible to edit the three existing Release messages via GitHub to add the notes to them? I've added Seq66 to the site linked above but the feed doesn't have that content.

**Comment by mxmilkiib** [comment]
Might it be possible to edit the [release](https://github.com/ahlstromcj/seq66/releases) to pop the release notes in?

**Comment by ahlstromcj** [comment]
I'll have to figure out the ins-and-outs of that.  Soon, baby, soon :-) 

-------- Milkii Brewster 07:22 Sun 07 Mar      --------

>Might it be possible to edit the [release](https://github.com/ahlstromcj/seq66/releases) to pop the release notes in?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/seq66/issues/24#issuecomment-792295865

-- 
A recent study has found that concentrating on difficult off-screen
objects, such as the faces of loved ones, causes eye strain in computer
scientists.  Researchers into the phenomenon cite the added concentration
needed to "make sense" of such unnatural three dimensional objects.

**Comment by mxmilkiib** [comment]
It's just that it's time sensitive as GitHub has [malformed releases.atom feeds](https://github.com/isaacs/github/issues/1892) that only have an updated date not a published date, so any change to the release details will change the date in the feed that is used by libreav.org.

**Comment by mxmilkiib** [comment]
The [NEWS file gets](https://github.com/ahlstromcj/seq66/commit/cee8ad568de8e5baf4a70c9538635ee2ac9b2eb3#diff-7ee66c4f1536ac84dc5bbff1b8312e2eef24b974b3e48a5c5c2bcfdf2eb8f3ceR9) all the change information, but the text of the release in git is wanting; 
![image](https://user-images.githubusercontent.com/108225/175794878-cbcba33c-d256-4fb0-bda8-8150ab8ee45d.png)

**Comment by ahlstromcj** [comment]
I added a release for 0.99.0 master.  I tried to use the hub command (the latest version download from github), but couldn't get it to work ("Not found") as I tried to document in contrib/git/git.text.  So I went via the github gui.  Bleh.  Let me know of issues; the release notes were created by running thunar and dragging RELNOTES.md on to the release notes textbox.

**Comment by mxmilkiib** [comment]
A link to the release notes file is better than nothing, if the tag message cannot be set as the newest notes

**Comment by ahlstromcj** [comment]
Yeah, these darn GUIs and their secret workings.  I expected the text to
be shown, not a link to the file.  Probably okay this time, because the release
notes this time around are huge.  Next time I will copy/paste the text
directly.  I'd prefer to get the hub command working, though. Sigh.

**Comment by ahlstromcj** [comment]
I tried to copy RELNOTES into the release message when tagging the latest version (0.99.3) but I made a slight mistake in the format and it did not work.  I figured out how to do it right and will make sure it works for the next release.  Dang.

**Comment by ahlstromcj** [comment]
I think I figured this out, and added notes to the git.text file.  Can you verify?

**Comment by mxmilkiib** [comment]
Yes, it appears that is coming through now. Thanks v much! :D

**Comment by mxmilkiib** [comment]
Could it please be possible to put the version number at the start or end of the title that you give a release? That title becomes the version string in the feed and thus can't get parsed by LibreAV. See the missing releases on https://libreav.org/software/seq66 Thanks for all your work!

**Comment by ahlstromcj** [comment]
Done. Couldn't do it on my phone last night, was at a Halloween pumpkin walk
with the grandsons!

**Comment by mxmilkiib** [comment]
I think you forgot to put the release number in the release title!

**Comment by ahlstromcj** [comment]
Doh!!!
